export const GET_ALL_BUSES = "GET_ALL_BUSES";
export const GET_BUS = "GET_BUS";
export const GET_ALL_STOPS = "GET_ALL_STOPS";
export const GET_USER_COORDS = "GET_USER_COORDS";
export const GET_QUICK_STATS = "GET_QUICK_STATS";
export const GET_ALL_ANNOUNCEMENT = "GET_ALL_ANNOUNCEMENT";
export const REFRESH_ANNOUNCEMENT = "REFRESH_ANNOUNCEMENT";
export const REFRESH_BUSES = "REFRESH_BUSES";
